### ISSUE TITLE
 A CropController was used after being disposed. E/flutter (20376): Once you have called dispose() on a CropController, it can no longer be used.

### ISSUE THREAD

**Issue by yeahse** [deakjahn/crop_image#15]
```
E/flutter (20376): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: A CropController was used after being disposed.
E/flutter (20376): Once you have called dispose() on a CropController, it can no longer be used.
E/flutter (20376): #0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:157:9)
E/flutter (20376): #1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:164:6)
E/flutter (20376): #2      ChangeNotifier.dispose (package:flutter/src/foundation/change_notifier.dart:323:27)
E/flutter (20376): #3      _ScreenAbcPostState.build.<anonymous closure> (package:abc/screens/abc/abc.post.dart:321:37)
E/flutter (20376): <asynchronous suspension>
```

I have never disposed but the above error occurs.

**Comment by joeldegerman99** [comment]
@yeahse If you look at the source code, the cropper itself disposes of the controller. This might not be your exact problem, but remember that if you view that the cropper is closed, the controller will be disposed of, so if you use it on another page, it can be disposed of before it is used

**Comment by victor7w7r** [comment]
> @yeahse If you look at the source code, the cropper itself disposes of the controller. This might not be your exact problem, but remember that if you view that the cropper is closed, the controller will be disposed of, so if you use it on another page, it can be disposed of before it is used

nope, same here

**Comment by deakjahn** [comment]
The message comes from Flutter, not the plugin directly.

Anyway, considering that the bundled example doesn't seem to show any such error, I'd need a reproducible demo to see what you're trying to do that causes this message.

**Comment by Hannnes1** [comment]
Hi, I just got the same error. It occurs when you create the controller yourself in a `StatefulWidget`, and then override `dispose` in that widget:

```dart
  @override
  void dispose() {
    _cropController.dispose();
    super.dispose();
  }
```

I haven't tested it yet, but i believe the cause of the issue is [here](https://github.com/deakjahn/crop_image/blob/b91aed7b570c3ba8110b0cc98a41e46231a87a7c/lib/src/crop_image.dart#LL179C1-L179C26).

As per the documentation of `dispose()`:

> This method should only be called by the object's owner.

So I believe that the solution would be to add a check if `widget.controller` is null or not, and only call `controller.dispose()` if it is.

**Comment by deakjahn** [comment]
Then if you would please, just test it simply, we could determine whether this is the cause indeed...

**Comment by Hannnes1** [comment]
That is indeed the issue. To clarify, this is the working code (in `crop_image.dart`):
```dart
  @override
  void dispose() {
    controller.removeListener(onChange);

    if (widget.controller == null) {
      controller.dispose();
    }

    _stream.removeListener(_streamListener);

    super.dispose();
  }
```

I also noticed that `didUpdateWidget` calls `controller.dispose()` if `widget.controller != null` as well. That might be an issue, but I wasn't able to cause any (I'm not entirely sure what its purpose is in the first place either). So it might be best to leave that as is. What do you think?

If you like I can open a pull request once I get a answer to the above. Or do you prefer to make the changes yourself?

**Comment by deakjahn** [comment]
A PR would be very nice, thanks.

It's normally called when the configuration of the widget is changed. To give you an example (not from this package, but generally), consider a widget that shows a value with a progress bar-like display, 50% value means half of the bar with a different color. If you always animate the bar to the current value, it will smoothly grow from zero to the actual value. If you now suppose that the value gets changed, say, from 50% to 75%, the naive approach would cause the animation to run again from zero to 75%. With `didUpdateWidget()`, you can get the changing configuration, the previous value and the current value, and act upon it: to make the value animate between the old (50%) and new (75%) values rather than from zero again. So, in general terms, you can use it whenever you need to handle both sides of the change, both the outgoing and the incoming state of the widget.
