### ISSUE TITLE
Revert also down to meta 1.8.0?

### ISSUE THREAD

**Issue by monsieurtanuki** [deakjahn/crop_image#26]
> Because every version of flutter_test from sdk depends on meta 1.8.0 and crop_image >=1.0.8 depends on meta ^1.9.1, flutter_test from sdk is incompatible with crop_image >=1.0.8.

**Comment by deakjahn** [comment]
I don't normally use `meta` for anything, so I don't know immediately where it was introduced at all. Maybe one of your PRs? :-) I would suggets to remove it altogether.

**Comment by monsieurtanuki** [comment]
@deakjahn You added `meta` at least [2 years ago](https://github.com/deakjahn/crop_image/blame/e1ab399f701491842b94c0351d677a2aca768af6/pubspec.yaml):
![Capture d’écran 2023-06-02 à 18 18 27](https://github.com/deakjahn/crop_image/assets/11576431/cf2eacc7-3cc0-4769-a3f5-6926bb436698)

As I come from Java, I do think it's much cleaner to use `meta` annotations, without having to play with file names, class names or method names.

**Comment by deakjahn** [comment]
Really? I wonder why... Now as I check it, it was in the dev dependencies part, only got moved up. Still doesn't answer why it was needed in the first place. :-) Yep, it was down there in the initial commit. I probably cloned another package to start this one, that's why.

Anyway, I'll remove it now. I only partly agree with you in this, namely, if it's an annotation that's part of the core language itself, then OK. But not to rely on an outside package just to do something that's not even necessary... And, after all, the underscore is Dart's own mechanism for visibility, not a hack but part of the language itself... :-)
