### ISSUE TITLE
Type 'ImageDecoderCallback' not found

### ISSUE THREAD

**Issue by alamin-karno** [deakjahn/crop_image#38]
After installing the package and if I wanted to run the package, then this error came out.

![Screenshot 2023-09-11 at 2 53 34 PM](https://github.com/deakjahn/crop_image/assets/56608168/814fe4fb-8c31-4cd6-a7cc-2ce508a89735)

The problem is that importing the UI is not correct. You'll need to fix that, or I can give it a try on it.

**Comment by deakjahn** [comment]
The "issue" -- which isn't really an issue at all -- has been pinned at the top of the queue so that you can find it easier: https://github.com/deakjahn/crop_image/issues/32

This isn't an issue. You're trying to use an old version of the Flutter SDK. Please, upgrade. The plugin won't be reverted back to an outdated, deprecated SDK any more.
