### ISSUE TITLE
Please explain it more .Can't understand this

### ISSUE THREAD

**Issue by expertdev-designer** [deakjahn/crop_image#6]
Creating a file 
If you want to get a file from the ui.Image, this is nothing specific to crop_image. Use the existing functions of Image and File:

data = await image.toByteData(format: ImageByteFormat.png);
bytes = data!.buffer.asUint8List();
file.writeAsBytes(bytes, flush);

@deakjahn @jasonttf Please Help
Thanks

**Comment by deakjahn** [comment]
It was already asked in the issue queue how you could save the cropped image to a file. While this has nothing to do with the plugin itself, I decided to include this fragment in the README in order to help.

So, if you need the same, to save the cropped image (one that you obtained with `await controller.croppedBitmap()`) then use these three lines, that's all.

**Comment by expertdev-designer** [comment]
> It was already asked in the issue queue how you could save the cropped image to a file. While this has nothing to do with the plugin itself, I decided to include this fragment in the README in order to help.
> 
> So, if you need the same, to save the cropped image (one that you obtained with `await controller.croppedBitmap()`) then use these three lines, that's all.

Okay Thanks
